version: '3.4'

services:
  mysql.school:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: vjzbeQ7XwMblL1SXdRR2U
      MYSQL_DATABASE: school
    volumes:
      - mysql.school.data:/var/lib/mysql

  redis.school:
    image: redis:latest
    command: redis-server
    ports:
      - 16379:6379
    volumes:
      - redis.school.data:/data

  api.school:
    image: api.school
    depends_on:
      - mysql.school
    ports:
      - 8080:8080
    environment:
      spring.datasource.url: jdbc:mysql://mysql.school:3306/school
      spring.redis.url: redis://redis.school:6379

volumes:
  mysql.school.data:
  redis.school.data:
